// @ts-ignore
import PDFDocument from 'pdfkit';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, AlignmentType } from 'docx';
import fs from 'fs';
import path from 'path';
import { MomContent, ActionItem } from '../types';
import { config } from '../config';

// Generate PDF
export async function generatePDF(mom: MomContent, meetingId: string): Promise<string> {
  const uploadsDir = config.upload.dir;
  const fileName = `mom_${meetingId}_${Date.now()}.pdf`;
  const filePath = path.join(uploadsDir, fileName);
  
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);
    
    doc.pipe(stream);
    
    // Header
    doc.fontSize(24).font('Helvetica-Bold').text('Acta', { align: 'center' });
    doc.fontSize(10).font('Helvetica').text('Minutes of Meeting', { align: 'center' });
    doc.moveDown(2);
    
    // Meeting Title
    doc.fontSize(18).font('Helvetica-Bold').text(mom.meeting.title);
    doc.moveDown(0.5);
    
    // Meeting Info
    doc.fontSize(10).font('Helvetica');
    doc.text(`Type: ${mom.meeting.type.replace('_', ' ').toUpperCase()}`);
    doc.text(`Date: ${new Date(mom.meeting.meeting_date).toLocaleDateString('en-US', { 
      weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
    })}`);
    if (mom.meeting.location) doc.text(`Location: ${mom.meeting.location}`);
    if (mom.meeting.duration_minutes) doc.text(`Duration: ${mom.meeting.duration_minutes} minutes`);
    doc.moveDown();
    
    // Objective
    if (mom.meeting.objective) {
      doc.fontSize(12).font('Helvetica-Bold').text('Objective');
      doc.fontSize(10).font('Helvetica').text(mom.meeting.objective);
      doc.moveDown();
    }
    
    // Participants
    doc.fontSize(12).font('Helvetica-Bold').text('Participants');
    mom.participants.forEach(p => {
      doc.fontSize(10).font('Helvetica').text(`• ${p.name}${p.email ? ` (${p.email})` : ''}${p.role !== 'attendee' ? ` - ${p.role}` : ''}`);
    });
    doc.moveDown();
    
    // Agenda
    if (mom.agenda_items.length > 0) {
      doc.fontSize(12).font('Helvetica-Bold').text('Agenda');
      mom.agenda_items.forEach((item, i) => {
        doc.fontSize(10).font('Helvetica').text(`${i + 1}. ${item.title}`);
        if (item.description) {
          doc.fontSize(9).text(`   ${item.description}`);
        }
      });
      doc.moveDown();
    }
    
    // Summary
    doc.fontSize(12).font('Helvetica-Bold').text('Summary');
    doc.fontSize(10).font('Helvetica').text(mom.summary);
    doc.moveDown();
    
    // Decisions
    if (mom.decisions.length > 0) {
      doc.fontSize(12).font('Helvetica-Bold').text('Key Decisions');
      mom.decisions.forEach(d => {
        doc.fontSize(10).font('Helvetica').text(`• ${d.content}${d.decided_by ? ` (${d.decided_by})` : ''}`);
      });
      doc.moveDown();
    }
    
    // Action Items
    if (mom.action_items.length > 0) {
      doc.fontSize(12).font('Helvetica-Bold').text('Action Items');
      doc.moveDown(0.5);
      
      // Table header
      const tableTop = doc.y;
      const col1 = 50, col2 = 250, col3 = 350, col4 = 420, col5 = 480;
      
      doc.fontSize(9).font('Helvetica-Bold');
      doc.text('Task', col1, tableTop);
      doc.text('Assignee', col2, tableTop);
      doc.text('Deadline', col3, tableTop);
      doc.text('Priority', col4, tableTop);
      doc.text('Status', col5, tableTop);
      
      doc.moveTo(col1, tableTop + 12).lineTo(550, tableTop + 12).stroke();
      
      let y = tableTop + 18;
      doc.font('Helvetica').fontSize(8);
      
      mom.action_items.forEach(item => {
        const taskText = item.title.substring(0, 40) + (item.title.length > 40 ? '...' : '');
        doc.text(taskText, col1, y, { width: 190 });
        doc.text(item.assignee_name || '-', col2, y);
        doc.text(item.deadline ? new Date(item.deadline).toLocaleDateString() : '-', col3, y);
        doc.text(item.priority.toUpperCase(), col4, y);
        doc.text(item.status, col5, y);
        y += 15;
      });
    }
    
    // Footer
    doc.fontSize(8).font('Helvetica').text(
      `Generated by Acta on ${new Date().toLocaleString()}`,
      50,
      doc.page.height - 50,
      { align: 'center' }
    );
    
    doc.end();
    
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

// Generate Word Document
export async function generateDocx(mom: MomContent, meetingId: string): Promise<string> {
  const uploadsDir = config.upload.dir;
  const fileName = `mom_${meetingId}_${Date.now()}.docx`;
  const filePath = path.join(uploadsDir, fileName);
  
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        // Header
        new Paragraph({
          children: [new TextRun({ text: 'Acta', bold: true, size: 48 })],
          alignment: AlignmentType.CENTER,
        }),
        new Paragraph({
          children: [new TextRun({ text: 'Minutes of Meeting', size: 20 })],
          alignment: AlignmentType.CENTER,
        }),
        new Paragraph({ text: '' }),
        
        // Title
        new Paragraph({
          text: mom.meeting.title,
          heading: HeadingLevel.HEADING_1,
        }),
        
        // Meeting Info
        new Paragraph({
          children: [
            new TextRun({ text: 'Type: ', bold: true }),
            new TextRun(mom.meeting.type.replace('_', ' ').toUpperCase()),
          ],
        }),
        new Paragraph({
          children: [
            new TextRun({ text: 'Date: ', bold: true }),
            new TextRun(new Date(mom.meeting.meeting_date).toLocaleDateString('en-US', {
              weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
            })),
          ],
        }),
        ...(mom.meeting.location ? [new Paragraph({
          children: [
            new TextRun({ text: 'Location: ', bold: true }),
            new TextRun(mom.meeting.location),
          ],
        })] : []),
        new Paragraph({ text: '' }),
        
        // Objective
        ...(mom.meeting.objective ? [
          new Paragraph({ text: 'Objective', heading: HeadingLevel.HEADING_2 }),
          new Paragraph({ text: mom.meeting.objective }),
          new Paragraph({ text: '' }),
        ] : []),
        
        // Participants
        new Paragraph({ text: 'Participants', heading: HeadingLevel.HEADING_2 }),
        ...mom.participants.map(p => new Paragraph({
          text: `• ${p.name}${p.email ? ` (${p.email})` : ''}${p.role !== 'attendee' ? ` - ${p.role}` : ''}`,
        })),
        new Paragraph({ text: '' }),
        
        // Summary
        new Paragraph({ text: 'Summary', heading: HeadingLevel.HEADING_2 }),
        new Paragraph({ text: mom.summary }),
        new Paragraph({ text: '' }),
        
        // Decisions
        ...(mom.decisions.length > 0 ? [
          new Paragraph({ text: 'Key Decisions', heading: HeadingLevel.HEADING_2 }),
          ...mom.decisions.map(d => new Paragraph({
            text: `• ${d.content}${d.decided_by ? ` (${d.decided_by})` : ''}`,
          })),
          new Paragraph({ text: '' }),
        ] : []),
        
        // Action Items
        ...(mom.action_items.length > 0 ? [
          new Paragraph({ text: 'Action Items', heading: HeadingLevel.HEADING_2 }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [
              new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph({ text: 'Task', bold: true } as any)] }),
                  new TableCell({ children: [new Paragraph({ text: 'Assignee', bold: true } as any)] }),
                  new TableCell({ children: [new Paragraph({ text: 'Deadline', bold: true } as any)] }),
                  new TableCell({ children: [new Paragraph({ text: 'Priority', bold: true } as any)] }),
                  new TableCell({ children: [new Paragraph({ text: 'Status', bold: true } as any)] }),
                ],
              }),
              ...mom.action_items.map(item => new TableRow({
                children: [
                  new TableCell({ children: [new Paragraph({ text: item.title })] }),
                  new TableCell({ children: [new Paragraph({ text: item.assignee_name || '-' })] }),
                  new TableCell({ children: [new Paragraph({ text: item.deadline ? new Date(item.deadline).toLocaleDateString() : '-' })] }),
                  new TableCell({ children: [new Paragraph({ text: item.priority.toUpperCase() })] }),
                  new TableCell({ children: [new Paragraph({ text: item.status })] }),
                ],
              })),
            ],
          }),
        ] : []),
        
        // Footer
        new Paragraph({ text: '' }),
        new Paragraph({
          children: [new TextRun({ text: `Generated by Acta on ${new Date().toLocaleString()}`, italics: true, size: 16 })],
          alignment: AlignmentType.CENTER,
        }),
      ],
    }],
  });
  
  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(filePath, buffer);
  
  return filePath;
}
